### ISSUE TITLE
Bot tried to place margin trades by default 

### ISSUE THREAD

**Issue by waupdog** [CyberPunkMetalHead/binance-dca-crypto-trading-bot#3]
When in live mode, bot tries to make margin trades instead of spot trades

**Comment by CyberPunkMetalHead** [comment]
Interesting, are you able to share the log?

**Comment by waupdog** [comment]
I don't think I need to. If you look in binance_service.py the create order method uses margin order from the binance API python package: 


def create_order(coin, amount, action):
    """
    Creates simple buy order and returns the order
    """
    return client.create_margin_order(
        symbol = coin,
        side = action,
        type = 'MARKET',
        quantity = amount
    )


I've made a fork with some changes, including changing this to a market spot order and some amendments to the calculation of quantity to ensure the minimum trade quantity is always met, if you'd like to check them out. I'm new to github so hopefully I've done this the right way!

**Comment by CyberPunkMetalHead** [comment]
My bad, you are correct, thanks! I have fixed this by switching from Margin to market Spot orders. I will take a look at your fork regarding your order quantity changes.
